### ISSUE TITLE
CPAN indexing of Email-MIME-RFC2047 does not show latest release version 0.95

### ISSUE THREAD

**Issue by Corin-EU** [nwellnhof/Email-MIME-RFC2047#3]
Please have a look at  https://github.com/metacpan/metacpan-api/issues/726 concerning a problem with CPAN indexing failing to show the latest release version of Email-MIME-RFC2047, viz it reports the old 0.93 version instead of the latest 0.95 version.

(I mistakenly thought this was a MetaCPAN API issue.)

**Comment by nwellnhof** [comment]
Fixed in version 0.96.

**Comment by Corin-EU** [comment]
Thanks for the fix.

All looks good now via MetaCPAN API

        "date" : "2017-07-27T18:07:23",
        "version" : "0.96",
        "status" : "latest",
        "download_url" : "https://cpan.metacpan.org/authors/id/N/NW/NWELLNHOF/Email-MIME-RFC2047-0.96.tar.gz"

**Comment by hvoers** [comment]
But now "man Email::MIME::RFC2047" does not give me the pod I need :(

Can you please insert the whole .pod file into RFC2047.pm ?

**Comment by nwellnhof** [comment]
> Can you please insert the whole .pod file into RFC2047.pm ?

Fixed in version 0.97.

**Comment by hvoers** [comment]
Thank you.
It's on it's way to the FreeBSD ports collection.
